[2023-12-11 16:55:06,804] ERROR log_exception() L825  Exception on /produto [GET] - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\app.py", line 94, in get_produto
    produto_id = query.id
                 ^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\pydantic\main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ProdutoBuscaSchema' object has no attribute 'id'
[2023-12-11 16:55:06,832] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:55:06] "[35m[1mGET /produto?nome=água HTTP/1.1[0m" 500 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:55:07,927] ERROR log_exception() L825  Exception on /produto [GET] - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\app.py", line 94, in get_produto
    produto_id = query.id
                 ^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\pydantic\main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ProdutoBuscaSchema' object has no attribute 'id'
[2023-12-11 16:55:07,936] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:55:07] "[35m[1mGET /produto?nome=água HTTP/1.1[0m" 500 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:55:14,585] ERROR log_exception() L825  Exception on /produto [GET] - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\app.py", line 94, in get_produto
    produto_id = query.id
                 ^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\pydantic\main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ProdutoBuscaSchema' object has no attribute 'id'
[2023-12-11 16:55:14,601] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:55:14] "[35m[1mGET /produto?nome=suco HTTP/1.1[0m" 500 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:55:33,608] ERROR log_exception() L825  Exception on /produto [GET] - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\app.py", line 94, in get_produto
    produto_id = query.id
                 ^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\pydantic\main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ProdutoBuscaSchema' object has no attribute 'id'
[2023-12-11 16:55:33,617] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:55:33] "[35m[1mGET /produto?nome=2 HTTP/1.1[0m" 500 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:56:09,252] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:56:09] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:56:11,758] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:56:11] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:59:15,412] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:59:15] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:59:17,027] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:59:17] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:59:49,392] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:59:49] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
